FROM confluentinc/cp-kafka-connect:7.6.1

ADD downloads/debezium-connector-postgres-2.5.4.Final-plugin.tar.gz /usr/share/confluent-hub-components/
COPY downloads/iceberg-kafka-connect /usr/share/confluent-hub-components/iceberg-kafka-connect
