FROM confluentinc/cp-kafka-connect:7.6.1

COPY downloads/debezium-debezium-connector-postgresql /usr/share/confluent-hub-components/debezium-debezium-connector-postgresql
COPY downloads/iceberg-kafka-connect /usr/share/confluent-hub-components/iceberg-kafka-connect
